### ISSUE TITLE
[RFC]typed: Generate Sample Config File from Schema

### ISSUE THREAD

**Issue by rochacbruno** [dynaconf/dynaconf#1140]
Given
```py

class Database(DictValue):
    """Represents a database connection"""
    host: Annotated[str, Doc("Database hostname")]
    port: Annotated[int, Doc("Database port"), Gt(5000)] = 5432

class Settings(Dynaconf):
    """Settings for XPTO system."""
    name: str
    debug: bool = False
    database: Database
    options: NotRequired[dict[str, Any]]
```

On the CLI:

```console
$ dynaconf -i config.settings generate-settings --format yaml > settings.yaml
```

Generates

```yaml
# Settings for XPTO System

# type: str
# required
name: 

# type: bool
# default False
debug: false

# type: dict
# Represents a database connection
# model: config.Database
database:
  # Database Hostname
  # type: str
  # required
  hostname:
  # Database port
  # type: int
  # > 5000
  # default 5432 
  port: 5432
 
# type: dict[str, Any]
# notrequired
# options:


```
