### ISSUE TITLE
[RFC]Change how  merge works on 4.0.0

### ISSUE THREAD

**Issue by rochacbruno** [dynaconf/dynaconf#1155]
Current merging works this way:

- Global merge is disabled by default, user must pass merge_enabled=True
- Global merge when enabled applies to branches (dicts) and leaves (lists)
- users can manually control merging by setting dynaconf_merge marks on dicts and lists

### dicts

- Merge of branches (dicts) will be enabled by default, there will be no way to disable it
- When user wants to skip the merge of a specific dict it will be needed to set the dynaconf_merge=False either on the settings sources or on the schema.
- Merge will then apply for all the childs of the marked dict

```py
class Database(DictValue):
    host: str
    port: int

class Settings(Dynaconf):
   database: Annotated[Database, Merge(False)]
```
or on a settings file
```toml
[database]
port = 123
dynaconf_merge = false
```
or on environment variable
```bash
export DYNACONF_DATABASE="@nomerge port=123,host='foo'"
```

For dictionaries the default will be merge when using `__` access (current behavior) and `@nomerge` when using comma separated, toml or json definition.

### lists

- Merge is disabled by default, incoming list always replaces the whole existing list
- User can explicitly set the list for merge using merge markers
- Schema can also default a list for merge

```py
class Settings(Dynaconf):
   plugin: Annotated[list, Merge(True, unique=True, mode="append|prepend")]
```
or on a settings file
```toml
plugins = ["great_plugin", "dynaconf_merge"]
plugins = ["great_plugin", "dynaconf_merge_unique"]
plugins = "@merge great_plugin"
plugins = "@append great_plugin"
plugins = "@insert 0 great_plugin"
plugins = "@replace 0 great_plugin"
plugins = "@insert after(thing) great_plugin"
plugins = "@insert before(thing) great_plugin"
plugins = "@slice 0..2 potato 3..6 chip 7.."
```
or on environment variable
```bash
# all the same merkers applies
export DYNACONF_PLUGINS="@merge ..."
```
