### ISSUE TITLE
[bug] An int type conf key in yaml complains when migrating

### ISSUE THREAD

**Issue by jyejare** [dynaconf/dynaconf#1161]
**Describe the bug**
When post dynaconf hook attempts to migrate the value under the `integer` type setting, dynaconf insists on being string when it tries to convert it to lower string.

Stacktrace:
```
File ~/venv/robottelo312/lib/python3.12/site-packages/dynaconf/utils/__init__.py:89, in object_merge(old, new, unique, full_path)
     83 if should_merge:
     84     for old_key, value in safe_items(old):
     85         # This is for when the dict exists internally
     86         # but the new value on the end of full path is the same
     87         if (
     88             existing_value is not None
---> 89             and old_key.lower() == full_path[-1].lower()
     90             and existing_value is value
     91         ):
     92             # Here Be The Dragons
     93             # This comparison needs to be smarter
     94             continue
     96         if old_key not in new:

AttributeError: 'int' object has no attribute 'lower'
```

**To Reproduce**

1. Having the following config files:

<details>
<summary> Setting file containing int type key </summary>

**/path/settings.yaml**
```yaml
compute_profile:
  attrs:
    cpus: 1
    memory: 2147483648
    nics_attributes:
      0:
        bridge: 'something_to_be_changed'
        model: virtio
        type: bridge
    volumes_attributes:
      0:
        allocation: 0G
        capacity: 10G
        format_type: raw
        pool_name: default
```

Here `0` is the integer type key.

</details>

3. Having the following app code:

<details>
<summary> Code migrating the setting to replace `something_to_be_changed` to `something_changed`  </summary>

**/path/src/app.py**
```python

for _key, _val in settings_list.items():
    if is_has_to_be(_val):
        data['compute_profile.attrs.nics_attributes.0.bridge'] = str(_val).replace('to_be', '')
        logger.debug(f'Setting translated to IPv6, Path: compute_profile.attrs.nics_attributes.0')
```

This code from a function is used in dynaconfs `post` function in `conf/` directory from where all the settings are being read by dynaconf.

</details>

**Expected behavior**
- Converting the setting under the integer type key should be successful.

**Environment (please complete the following information):**
 - OS: Any
 - Dynaconf Version: 3.2.5
 - Frameworks in use: Pytest

**Additional context**

**Comment by rochacbruno** [comment]
Hi thanks for reporting, looks like we need to add a `tests_functional/issues` to reproduce the problem and then change the lines

```py
     87         if (
     88             existing_value is not None
---> 89             and old_key.lower() == full_path[-1].lower()
     90             and existing_value is value
     91         ):
```

to make a check for `isinstance(str)` before lowering.

**Comment by sebastian-correa** [comment]
Thanks for the example @jyejare. I was about to implement @rochacbruno's suggestion here but noticed you mentioned a YAML.

I think this behavior is more related to the YAML spec than to Dynaconf itself. YAML has implicit type casting (outlined in [section 10.3.2](https://yaml.org/spec/1.2.2/#1032-tag-resolution) of the spec), so the behavior exhibited by Dynaconf is congruent with that (because the loader already outputs the `0` as an `int` and not a `str`). You can check this by doing:

```python
from dynaconf import Dynaconf

settings = Dynaconf(
    settings_files="test_settings.yaml"
)

print(settings["compute_profile"])

assert isinstance(list(settings["compute_profile"]["attrs"]["nics_attributes"].keys())[0], int)
assert not isinstance(list(settings["compute_profile"]["attrs"]["nics_attributes"].keys())[0], str)
```

I'm not super familiar with the TOML spec, but if you define this `test_settings.toml`
```toml
[compute_profile.attrs]
cpus = 1
memory = 2147483648

[compute_profile.attrs.nics_attributes.0]
bridge = "something_to_be_changed"
model = "virtio"
type = "bridge"

[compute_profile.attrs.volumes_attributes.0]
allocation = "0G"
capacity = "10G"
format_type = "raw"
pool_name = "default"

[1]
test = "test"
```

and do

```python
with open("test_settings.toml", "rb") as file:
    t = tomllib.load(file)
```
you'll get
```python
{'compute_profile': {'attrs': {'cpus': 1,
   'memory': 2147483648,
   'nics_attributes': {'0': {'bridge': 'something_to_be_changed',
     'model': 'virtio',
     'type': 'bridge'}},
   'volumes_attributes': {'0': {'allocation': '0G',
     'capacity': '10G',
     'format_type': 'raw',
     'pool_name': 'default'}}}},
 '1': {'test': 'test'}}
```

where these keys are strings already (though as far as I knew, TOML did support ints as keys 🤔).

I think that Dynaconf should decide if it wants to support arbitrary types in keys or just strings (I'm inclined to this option), as this error can also happen with other types that YAML (or any arbitrary loader) converts to, such as:

```yaml
some_weird_things:
  2024-01-01: "new_year"
```

which gets converted to
```python
{'some_weird_things': {datetime.date(2024, 1, 1): 'new_year'}}
```

I might be way off base here, only just starting to familiarize myself with Dynaconf's internals. What do you think @rochacbruno?

---

To clarify: not opposed to the fix Bruno mentioned, and can implement it if we decide to do so, but I'd like to give this some more though.
