### ISSUE TITLE
Environment variable for array

### ISSUE THREAD

**Issue by molntamas** [dynaconf/dynaconf#1165]
I have this kind of YAML config:
```
default:   
  SETTINGS:     
    - NAME: test1 	
      VALUE: value1
    - NAME: test2
      VALUe: value2
```

I'm wondering how I can override the settings "test1", "value1", etc. via environment variables?
Or if it is possible to add a new setting with environment variable for default_SETTINGS__0__NEW_SETTING="value".
I was checking documentation and some GitHub Issues but couldn't make it work.
Thank you!
