### ISSUE TITLE
[RFC] provide a way to add customized yaml loaders

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [dynaconf/dynaconf#611]
**Is your feature request related to a problem? Please describe.**

i want to use yaml loaders to add own lazy laoders to a dynaconf config

**Describe the solution you'd like**

```yaml
# settings.default.yaml
users:
   special_user:
      username: tester
      password: !from_vault
        path: secrets/qe/stage/users/tester
        key: password
 ```

```python
# settings.py
settings = Settings(settings_module=["settings.*.yaml"], YAML_LOADER_FOR_DYNACONF=my_enhanced_loader)
assert settings.users.special_user.password == "123abc"
```

**Describe alternatives you've considered**

im currently monkeypatching a yaml loader into dynaconfs vendored ruamel yaml, i loathe that solution
