### ISSUE TITLE
Hierarchy in .secrets.toml overwrites settings in settings.toml

### ISSUE THREAD

**Issue by m4rc3l-h3** [dynaconf/dynaconf#649]
Thanks for the great library and your support!

**Describe the bug**
Using hierarchy in .secrets.toml overwrites settings in settings.toml.

**To Reproduce**

1. Having the following folder structure
<details>
<summary> Project structure </summary>

```bash
files/testing/settings.toml
files/testing/.secrets.toml
src/main.py
```
</details>

2. Having the following config files:

<details>
<summary> Config files </summary>

files/testing/settings.toml
```toml
[default]
[default.db]
    name="name_default"
```

and

files/testing/.secrets.toml**
```toml
[default]
[default.db]
    password = 'default_password'
```

</details>

3. Having the following app code:

<details>
<summary> Code </summary>

**/src/main.py**
```python
from dynaconf import LazySettings

settings = LazySettings(
    environments=True,
    ENV_FOR_DYNACONF="default",
    ENVVAR_PREFIX_FOR_DYNACONF="none",
    load_dotenv=True,
    settings_files="../files/testing/settings.toml;../files/testing/.secrets.toml",
)

print(settings.db)
```
</details>

4. Executing under the following environment

<details>
<summary> Execution </summary>

```bash
$ python3 ./src/main.py
```

</details>

**Actual behavior**
Print: {'password': 'default_password'}

**Expected behavior**
Print: {'name': 'name_default', 'password': 'default_password'}

**Environment (please complete the following information):**
 - OS:  Linux 10 (buster)
-  Python: 3.9.1
 - Dynaconf Version: 3.1.5
 - Frameworks in use: none

**Additional context**
Removing hierarchy from .secrets.toml results in expected behavior:

Changing
**files/testing/.secrets.toml**

<details>

```toml
[default]
password = 'default_password'
```
</details>

and

**/src/main.py**

<details>

```python
from dynaconf import LazySettings

settings = LazySettings(
    environments=True,
    ENV_FOR_DYNACONF="default",
    ENVVAR_PREFIX_FOR_DYNACONF="none",
    load_dotenv=True,
    settings_files="../files/testing/settings.toml;../files/testing/.secrets.toml",
)

print(settings.db)
print(settings.password)
```

</details>

Results in the following output:
```bash
{'name': 'name_default'}
default_password
```

**Comment by m4rc3l-h3** [comment]
In addition, when using 
```python
settings.setenv('testing')
```
to change the environment, hierarchical settings in the default section are removed. Again, not using hierarchies does result in the expected behavior.

**Expected behavior**
Print: {'name': 'name_testing', 'port': '3307'}

**Actual behavior**
Print: {'name': 'name_testing'}

using the same configuration as described above, but changing the following:

**/files/testing/settings.toml**
```toml
[default]
[default.db]
    name="name_default"
    port="3307"

[testing]
[testing.db]
    name="name_testing"
```
