### ISSUE TITLE
Add custom converters to the docs

### ISSUE THREAD

**Issue by rochacbruno** [dynaconf/dynaconf#790]
The PR https://github.com/dynaconf/dynaconf/pull/784

allowed 

```py
# app.py
from pathlib import Path
from dynaconf.utils import parse_conf

parse_conf.converters["@path"] = (
    lambda value: value.set_casting(Path)
    if isinstance(value, parse_conf.Lazy)
    else Path(value)
)
```
```toml
# settings.toml

parent = "@path @format {env[HOME]}/parent"
child = "@path @format {this.parent}/child"
```

We need to add that to the docs and `example/` test run
