### ISSUE TITLE
[bug] `secret.yml` for nested Django settings work not as expected

### ISSUE THREAD

**Issue by Guo-Zhang** [dynaconf/dynaconf#827]
For example, if we have `DATABASES` as like:

```yaml
default:
  DATABASES:
    ENGINE: <your-engine>
```

When some secrets are configured in the `secret.yml` instead of `.env` file,

```yaml
development:
  DATABASES:
    PASSWORD: <your-password>
```

The engine configure will be replaced by default engine. It will work if 

```yaml
development:
  DATABASES:
     ENGINE: <your-engine>
     PASSWORD: <your-password>
```

or config it in the `default` part.

I am not sure whether it is a bug or a feature. Documentation doesn't see more about that.

**Comment by rochacbruno** [comment]
it is not a bug this the way dynaconf default merging strategy works,
we have to improve docs about it

what you can do is:

```yaml
development:
    dynaconf_merge: true
    DATABASES:
        ...
```

or the alternative

```yaml
development:
    DATABASES__PASSWORD: foobar123
```
