### ISSUE TITLE
How to dunder/merge/append to an array configuration?

### ISSUE THREAD

**Issue by wgordon17** [dynaconf/dynaconf#896]
For example, in a Django application, if I have in a `settings.yaml`

```yaml
default:
  TEMPLATES:
    - OPTIONS:
        context_processors:
          - django.template.context_processors.debug
          - django.template.context_processors.request
          - django.contrib.auth.context_processors.auth
```

And I want to append another context_processor in my `settings.local.yaml` file, how can I do that without overriding the entire array?

**Comment by pedro-psb** [comment]
In django, `TEMPLATES` is a dict like object, so its children shouldn't have the dash (which implies list/array).

```diff
default:
  TEMPLATES:
---     - OPTIONS: 
+++     OPTIONS:
        context_processors:
          - my.new.context.processor
```

Then this will enable merge for TEMPLATES and their nested values, which will achieve what you want.

```diff
default:
  TEMPLATES:
+++ dynaconf_merge: true
    OPTIONS:
        context_processors:
          - my.new.context.processor
```

**Comment by rochacbruno** [comment]
TEMPLATES is in fact a `List[dict]` and in this case there is no way yet to merge, this feature has been tracked on #299  https://github.com/dynaconf/dynaconf/issues/299#issuecomment-900616706

Right now the only possible workaround to this is using [dynaconf_hooks](https://www.dynaconf.com/advanced/?h=hooks#hooks-for-the-solution) which is not the ideal solution.

I want to implement the solution described on that issue, then the syntax would be 

```yaml
default:
    TEMPLATES="@merge_at 0 OPTIONS__context_processors=['social_django.context_processors.backends', 'social_django.context_processors.login_redirect', 'dynaconf_merge']"
```

Or something like

```yaml
default:
    TEMPLATES:
        - dynaconf_merge_at_0: {new data}
        # OR
       - dynaconf_append: {new_data}
```
