### ISSUE TITLE
[bug] AttributeError is thrown if one of the configuration keys is an integer

### ISSUE THREAD

**Issue by ogajduse** [dynaconf/dynaconf#919]
**Describe the bug**
Dynaconf fails to validate settings if any of the configuration keys are integer. Wrapping the key in quotes fixes the issue, but I would prefer dynaconf to keep its behavior from `3.1.11` where it did handle the integer-like keys correctly without throwing an exception.

**To Reproduce**
* have dynaconf 3.1.12 installed, I could not reproduce the bug with 3.1.11.
* initialize LazySettings
* validate settings

Project: [robottelo](https://github.com/SatelliteQE/robottelo/blob/b4b471aac102cfaeb40cffda7cd8452f1a2c1e1f/robottelo/config/__init__.py#L34)

Having the following config files:

<details>
<summary> Config files </summary>

**conf/ldap.yaml**
```yaml
LDAP:
  HOSTNAME:
    2016: env-ad-2016.acme.com
    2019: env-ad-2019.acme.com
  USERNAME: foobar
  PASSWORD: '@format {this.vault_awesome_password}'
  BASEDN: cn=Users,dc=department1,dc=loc1,dc=acme,dc=com
  GRPBASEDN: dc=department1,dc=loc1,dc=acme,dc=com
  REALM: INFRA.DEPARTMENT1.ACME.COM
  NAMESERVER:
    2016: 10.22.33.42
    2019: 10.22.33.43
  WORKGROUP:
    2016: SUBDEPT1
    2019: SUBDEPT12019
```

</details>

3. Having the following app code:
* [link to the repository](https://github.com/SatelliteQE/robottelo/blob/b4b471aac102cfaeb40cffda7cd8452f1a2c1e1f/robottelo/config/__init__.py#L19-L34)

4. Executing under the following environment

<details>
<summary> Execution </summary>

```bash
$ python -c 'from robottelo.config import settings'
```

</details>

**Expected behavior**
Dynaconf not throwing an AttributeError. Dynaconf should handle keys that are not strings as it did in version `3.1.11`.

**Environment (please complete the following information):**
 - OS: Fedora 36
 - Python 3.11
 - Dynaconf Version: 3.1.12
 - Frameworks in use: none
